version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
